config/routes.rb
Encuestas::Application.routes.draw do
  

  namespace :aspirante do
     resource :session , :only =>[:new, :create,:destroy]   
   end

  resource :cuestionario, :only =>[:new,:edit]
  resource :respuestas, :only =>[:create,:update]
  root :to => 'home#index'
  

end

app/models/cuestionario.rb
class Cuestionario < ActiveRecord::Base
  has_many :secciones, :class_name => 'Seccion', :foreign_key => 'cp_cst_cve_cst'
   
   def after_find
     arma_cuestionario
   end
   
   private
   def arma_cuestionario
        puts "Seccion.secciones_por_cst_y_gpo_preg("+self.cst_cve+","+self.cst_gpo_preg+")"
       self.secciones = Seccion.secciones_por_cst_y_gpo_preg(self.cst_cve,self.cst_gpo_preg)
       self.secciones.each do |seccion|
         seccion.preguntas = Pregunta.preguntas_por_cve_preg(seccion.cp_cst_cve_preg)
         seccion.preguntas.each do |pregunta|
           pregunta.opciones = Opcion.opciones_por_cve_opcion(pregunta.prg_gpo_op)
         end
       end
       
   end
   
end

app/controllers/cuestionario_controller.rb
class CuestionarioController < ApplicationController
  def index
    @aspi = Aspirante.new
  end

  def show
  end

end

app/controllers/cuestionarios_controller.rb
class CuestionariosController < ApplicationController
  before_filter :inicio_requerido
  
  def new
    @cuestionarios = Cuestionario.where(:cst_cve => session[:cuestionario])
  end
  #Seccion.secciones_por_cst_y_gpo_preg(cuestionario.cst_cve,cuestionario.cst_gpo_preg)
  #Pregunta.preguntas_por_cve_preg(seccion.cp_cst_cve_preg)
  #Opcion.opciones_por_cve_opcion(pregunta.prg_gpo_op)
  def edit
    @cuestionarios = Cuestionario.where(:cst_cve => session[:cuestionario])
    @Seccion.where(:cp_cst_cve_cst => session[:cuestionario])   
    @preguntas = Pregunta.select("prg_cve_preg,prg_ini,prg_fin").where("prg_cve_preg in ("+genera_in_preguntas(@secciones)+")")
    #@selecciones = Conversor.selecciones(@preguntas, Respuesta.find_by_enc_id(session[:usuario].comprobante))    
  end
  
  
  
  private 
  def genera_in_preguntas(secciones)
    inn = ""
    secciones.each do |sec|
      inn += "'"+sec.cp_cst_cve_preg+"',"
    end
    inn[inn.size-1]=""
    inn
  end
  
end

app/helpers/cuestionario_helper.rb
module CuestionarioHelper
  def preg_select(tipo)
    if tipo=="01"
      return select_tag 'pregunta'
    end
  end
  
  def campo_fijo(cve_preg)
    case cve_preg
    when "000"
      return session[:usuario].apellido_pat+session[:usuario].apellido_mat+session[:usuario].nombre
    when "038"
      return session[:usuario].comprobante
    when "003"
      return session[:usuario].fec_nac
    when "004"
      return session[:usuario].sexo
    end
  end
  
  def contenido_por_tipo_preg(pregunta)
    case pregunta.prg_tipo

    when "01"
      return 
          "<td>
            %font{:size=>'2'}
              - if pregunta.prg_cve_subpreg == '000'
                = num
                = '.-'
              = pregunta.prg_txt
          %td
            %font{:size=>'2'}"
              #= select_tag 'pregunta', options_from_collection_for_select(Opcion.opciones_por_cve_opcion(pregunta.prg_gpo_op),:opc_cve_op, :opc_txt)
    else
      return ""
    end
      
  end  
  
  
  #????
  def options_for_select(container, selected = nil)
    return container if String == container
    container = container.to_a if Hash==container
    selected,disable = extract_selected_and_disabled(selected).map do |r|
      Array.wrap(r).map{|item| item.to_s}
    end
    container.map do |element| 
      html_attributes = option_html_attributes(element)
      text, value = option_text_and_value (element).map{|item| item.to_s}
      selected_attribute = ' selected ="selected "' if option_value_selected?(value,selected)
      disable_attribute = ' disable = "disable"' if disable && option_value_selected?(value,disable)
      %(<option value = "#{html_escape(value)}"#{selected_attribute}#{disable_attribute}#{html_attributes}>#{html_escape(raw(text))}</option>)
    end.join("\n").html_safe
    
  end
  
end

app/views/cuestionarios/_cuestionario.haml
%tr
  %td{:width => "100%", :colspan => "3"}
    .titulosseccion{:align => "center"}
      %b 
        = raw(cuestionario.cst_txt)
= render :partial => 'seccion' , :collection => Seccion.secciones_por_cst_y_gpo_preg(cuestionario.cst_cve,cuestionario.cst_gpo_preg), :locals => {:select => select}

app/views/cuestionarios/_cuestionario_cabezera.html.haml
%hr
%h5
  %center
    = raw(cuestionario.cst_txt)
%hr

app/views/cuestionarios/_pregunta.html.haml
%tr{:id => "azulobscuro"}
  %td{:align => "right"}
    %font{:size=>"2"}
      -case pregunta.prg_tipo
      -when "02"
      -	else
        - if pregunta.prg_cve_subpreg == "000"
          = num
          = ".-"
      =  raw(pregunta.prg_txt)+":"+raw("&nbsp;")
    %td
      %font{:size=>"2"}
        - case pregunta.prg_tipo
        - when "00"
          = campo_fijo(pregunta.prg_cve_preg)
        - when "01"
          = select_tag pregunta.prg_cve_preg+"_"+pregunta.prg_ini+"_"+pregunta.prg_fin, options_from_collection_for_select(Opcion.opciones_por_cve_opcion(pregunta.prg_gpo_op),:opc_cve_op, :opc_txt,  :selected => select[pregunta.prg_cve_preg+"_"+pregunta.prg_ini+"_"+pregunta.prg_fin]), :obligatorio => pregunta.prg_tipo_oblig

        - when "07" 
          = select_tag pregunta.prg_cve_preg+"_"+pregunta.prg_ini+"_"+pregunta.prg_fin, options_from_collection_for_select(Opcion.opciones_por_cve_opcion(pregunta.prg_gpo_op),:opc_cve_op, :opc_txt,:selected => ["001","002"]), :multiple => true, :obligatorio => pregunta.prg_tipo_oblig
        - when "02"

app/views/cuestionarios/_seccion.html.haml
= render :partial => 'pregunta' , :collection => Pregunta.preguntas_por_cve_preg(seccion.cp_cst_cve_preg), :locals =>{:num => seccion.cp_cst_num_preg, :select => select}

app/views/cuestionarios/edit.html.haml
= render :partial => 'cuestionario_cabezera', :locals => {:cuestionario => @cuestionarios.first}
- form_tag '/respuestas', :method => :put do 
  %table{:id => "preguntas"}
    = render :partial => 'cuestionario', :collection => @cuestionarios[1..@cuestionarios.size-1] ,:locals => {:select => @selecciones}
  %hr
  = submit_tag "Guardar Datos (Si no has concluido podrás hacerlo despues)" ,:id =>"commit"
= link_to "salir" ,aspirante_session_path , :method => 'delete'

app/views/cuestionarios/new.html.haml
= render :partial => 'cuestionario_cabezera', :locals => {:cuestionario => @cuestionarios.first}
- form_tag '/respuestas' do 
  %table{:id => "preguntas"}
    = render :partial => 'cuestionario', :collection => @cuestionarios[1..@cuestionarios.size-1] ,:locals => {:select => {}}
  %hr
  = submit_tag "Guardar Datos (Si no has concluido podrás hacerlo despues)" ,:id =>"commit"
= link_to "salir" ,aspirante_session_path, :method => :delete

app/views/cuestionarios/show.html.haml
= render :partial => 'cuestionario_cabezera', :locals => {:cuestionario => @cuestionarios.first}
%table
  = render :partial => 'cuestionario', :collection => @cuestionarios[1..@cuestionarios.size-1]
= link_to "salir" ,aspirante_session_path, :method => :delete